apiVersion: v1
kind: Service
metadata:
    name: "kubernetestest-416b"
    labels:
        app: "kubernetestest-416b"
spec:
    type: LoadBalancer
    ports:
    - port: 7000
      targetPort: 7000
      protocol: TCP
      name: http
    selector:
        app: "kubernetestest-416b"